name: test

on:
  push:
  # pull_request:

jobs:
  zenodo_upload:
    name: zenodo upload
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      TZ: America/New_York

    steps:
      - name: Set env vars
        run: |
          export ZENODO_TOKEN=${{ secrets.ZENODO_TOKEN }}
          echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >> $GITHUB_ENV

          export GHA_TOKEN=${{ secrets.GHA_TOKEN }}
          echo "GHA_TOKEN=${GHA_TOKEN}" >> $GITHUB_ENV

      - name: checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: pip-install dependencies
        run: |
          python3 -m pip install requests

      - name: download artifacts
        run: |
          set -vxeuo pipefail

          #
          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection/actions/runs/6893976610
          #

          # # https://github.com/nsls2-conda-envs/nsls2-collection/suites/18255528211/artifacts/1055088073
          # bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection 1055088073 2023-3.3-py310

          # https://github.com/nsls2-conda-envs/nsls2-collection/suites/18255528211/artifacts/1055088080
          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection 1055088080 2023-3.3-py311

          #
          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/6893985933
          #

          # # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/suites/18255550871/artifacts/1055091555
          # bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 1055091555 2023-3.3-py310-tiled

          # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/suites/18255550871/artifacts/1055091561
          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 1055091555 2023-3.3-py311-tiled

      - name: Upload artifacts to Zenodo
        run: |
          python3 test-upload.py
