name: test

on:
  push:
  # pull_request:

jobs:
  zenodo_upload:
    name: zenodo upload
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      TZ: America/New_York

    steps:
      - name: Set env vars
        run: |
          export ZENODO_TOKEN=${{ secrets.ZENODO_TOKEN }}
          echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >> $GITHUB_ENV

          export GHA_TOKEN=${{ secrets.GHA_TOKEN }}
          echo "GHA_TOKEN=${GHA_TOKEN}" >> $GITHUB_ENV

      - name: checkout the code
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.10"

      - name: pip-install dependencies
        run: |
          python3 -m pip install requests

      - name: download artifacts
        run: |
          set -vxeuo pipefail

          #
          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection/actions/runs/5416168747
          #

          # https://github.com/nsls2-conda-envs/nsls2-collection/suites/13962286137/artifacts/778232809
          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection 778232809 2023-2.1-py310

          #
          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/5416167608
          #

          # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/suites/13962282224/artifacts/778231137
          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 778231137 2023-2.1-py310-tiled

      - name: Upload artifacts to Zenodo
        run: |
          python3 test-upload.py
