name: test

on:
  push:
  # pull_request:

jobs:
  test_zenodo_upload:
    name: download with wget
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |
          export ZENODO_SANDBOX_TOKEN=${{ secrets.ZENODO_SANDBOX_TOKEN }}
          echo "ZENODO_SANDBOX_TOKEN=${ZENODO_SANDBOX_TOKEN}" >> $GITHUB_ENV

      - name: checkout the code
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: 3.9

      - name: pip-install dependencies
        run: |
          python3 -m pip install requests

      - name: Test upload to Zenodo Sandbox
        run: |
          python3 test-upload.py
