name: test

on:
  push:
  # pull_request:

jobs:
  zenodo_upload:
    name: zenodo upload
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      TZ: America/New_York

    steps:
      - name: Set env vars
        run: |
          export ZENODO_TOKEN=${{ secrets.ZENODO_TOKEN }}
          echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >> $GITHUB_ENV

          export GHA_TOKEN=${{ secrets.GHA_TOKEN }}
          echo "GHA_TOKEN=${GHA_TOKEN}" >> $GITHUB_ENV

      - name: checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: pip-install dependencies
        run: |
          python3 -m pip install requests

      - name: download artifacts
        run: |
          set -vxeuo pipefail

          #
          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection/actions/runs/6696329405
          #

          # https://github.com/nsls2-conda-envs/nsls2-collection/suites/17755713829/artifacts/1017093217
          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection 1017093217 2023-3.2-py310

          #
          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/6674274136
          #

          # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/suites/17706989798/artifacts/1013563662
          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 1013563662 2023-3.2-py310-tiled

      - name: Upload artifacts to Zenodo
        run: |
          python3 test-upload.py
