name: Upload artifacts to Zenodo

on:
  push:
  # pull_request:

jobs:
  zenodo_upload:
    name: zenodo upload
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      TZ: America/New_York

    steps:
#      - name: Set env vars
#        run: |
#          export ZENODO_TOKEN=${{ secrets.ZENODO_TOKEN }}
#          echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >> $GITHUB_ENV
#
#          export GHA_TOKEN=${{ secrets.GHA_TOKEN }}
#          echo "GHA_TOKEN=${GHA_TOKEN}" >> $GITHUB_ENV

      - name: checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: pip-install dependencies
        run: |
          python3 -m pip install requests
      - name: download artifacts v2
        env:
          WORKFLOW_IDS: "9615874852 9615874852"
          GH_TOKEN: ${{github.token}}
        run: |
          python3 parse_for_artifacts.py -a "$WORKFLOW_IDS"
#          IFS=' ' read -r -a input_array <<< "$WORKFLOW_IDS"
#          for element in "${input_array[@]}"; do
#            echo "$element"
#          done

#      - name: download artifacts
#        run: |
#          set -vxeuo pipefail
#
#          # #
#          # # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection/actions/runs/7603753363
#          # #
#
#          # # https://github.com/nsls2-conda-envs/nsls2-collection/actions/runs/7603753363/artifacts/1184244620
#          # bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection 1184244620 2024-1.0-py310
#
#          # # https://github.com/nsls2-conda-envs/nsls2-collection/actions/runs/7603753363/artifacts/1184244622
#          # bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection 1184244622 2024-1.0-py311
#
#          #
#          # Artifacts from https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/9615874852
#          #
#
#          # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/9615874852/artifacts/1625317555
#          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 1625317555 2024-2.1-py310-tiled
#
#          # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/9615874852/artifacts/1625326776
#          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 1625326776 2024-2.1-py311-tiled
#
#          # https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/9615874852/artifacts/1625315849
#          bash ${GITHUB_WORKSPACE}/download-artifacts.sh nsls2-collection-tiled 1625315849 2024-2.1-py312-tiled
#      - name: Upload artifacts to Zenodo
#        run: |
#          python3 upload-artifacts.py
